### PR TITLE
styled the tour button

### PR DESCRIPTION
**Pull request by a-Cash-dixit**

### CODE REVIEW

**Comment by somya51p** [comment]
Screenshot from 2021-09-15 10-45-28
Screenshot from 2021-09-15 10-45-43
 Please look into that!

**Comment by a-Cash-dixit** [comment]
###

**Comment by a-Cash-dixit** [comment]
It is showing correctly on my system.

**Comment by somya51p** [comment]
> It is showing correctly on my system.

You need to check for different screen sizes and it should be completely responsive

**Comment by a-Cash-dixit** [comment]
Now check...

**Pull request merged**
