### PR TITLE
added new favicon svg type

### PR DESCRIPTION
**Pull request by a-Cash-dixit**

### CODE REVIEW

**Comment by somya51p** [comment]
@a-Cash-dixit Please attach the screenshot of the displayed favicon, when I am checking it I am unable to find the correct one.
Also upstream your current branch with the main of this repo.

**Comment by a-Cash-dixit** [comment]
It was showing on my machine. I have added the Bulb favicon.

**Comment by somya51p** [comment]
@a-Cash-dixit Attach the screenshot in that case and also use the **logo of the ERS website** as a favicon

**Comment by a-Cash-dixit** [comment]
Ok, will do that.

**Pull request closed without merging**
